name = "FITSexplore"
uuid = "8adab973-ac17-4ec6-8b81-43cd6f4779d2"
authors = ["Ferréol Soulez <ferreol.soulez@univ-lyon1.fr>"]
version = "0.1.0"

[workspace]
projects = ["test"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
ArgParse = "1"
FITSIO = "0.17"
StatsBase = "0.34"
UnicodePlots = "3"
julia = "1.9"
