name: CI
on:
  push:
    branches:
      - master
    tags: ["*"]
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
          - "lts"
          - "pre"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: FerreolS/FITSexplore.jl

  cli-bundle:
    name: CLI bundle workflow
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      actions: write
      contents: read
    env:
      JULIAC_ENV: /tmp/juliac-env-ci
      BUNDLE_DIR: build-juliac-ci
      EXE_NAME: fitsexplore
      TRIM_MODE: safe
      EXPERIMENTAL: "1"
      INSTALL_ROOT: /tmp/fitsexplore-install/fitsexplore-bundle
      BIN_DIR: /tmp/fitsexplore-install/bin
    steps:
      - uses: actions/checkout@v6

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.12"
          arch: x64

      - uses: julia-actions/cache@v3

      - name: Makefile help target
        run: make help

      - name: Build bundle via Makefile wrapper
        run: make build

      - name: Check built executable exists
        run: test -x "${BUNDLE_DIR}/bin/${EXE_NAME}"

      - name: Smoke test bundled executable
        run: |
          "${BUNDLE_DIR}/bin/${EXE_NAME}" --help

      - name: Install and uninstall via Julia script subcommands
        run: |
          julia --color=yes make.jl install
          test -L "${BIN_DIR}/${EXE_NAME}"
          test -x "${INSTALL_ROOT}/bin/${EXE_NAME}"
          julia --color=yes make.jl uninstall
          [ ! -e "${BIN_DIR}/${EXE_NAME}" ]

      - name: Clean via Makefile wrapper
        run: |
          make clean
          test ! -d "${BUNDLE_DIR}"

  Aqua:
    name: Aqua tests
    runs-on: ubuntu-latest
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - uses: julia-actions/cache@v3
      - run: julia --project=test --color=yes -e 'using Pkg; Pkg.add("Aqua")'
      - run: julia --project=test --color=yes -e 'using Aqua, FITSexplore; Aqua.test_all(FITSexplore)'
